// S05 synthetic UI data. No customer records, platform access or model calls.
import { referenceProductFixture } from './reference-product-fixture';
import type { ProductIntelligenceView, ProductTrafficBatchView } from '../src/data/localPlatformService';

export function productFixture(caseName = 'normal'): ProductIntelligenceView {
  const data = structuredClone(referenceProductFixture) as unknown as ProductIntelligenceView;
  const benchmark = {keyword:'合成页面开发',sample_days:0,high_visibility_result_count:0,priced_result_count:0,repeated_result_count:0,median_price:null,price_low:null,price_high:null,common_title_terms:[],common_tags:[],median_title_length:null,confidence:'low',evidence:['合成状态：尚无多日市场证据。']};
  data.market_reference = {date:'2026-09-17',mode:'recommended',selected_keyword:'合成页面开发',custom_keyword:'',common_keywords:[],recommendations:[{keyword:'合成页面开发',theme:'页面开发',score:1,reason:'隔离验收示例，不是市场结论',evidence:[],confidence:'low'}],current_sample:null,recent_samples:[],stability:{keyword:'合成页面开发',sample_days:0,visible_days:0,average_best_position:null,status:'insufficient',label:'样本不足'},benchmark,reminder:{date:'2026-09-17',status:'pending',scheduled_for:'2026-09-17T12:00:00Z',due:false,snoozed_until:null},update_completed:false,last_updated_at:null,rules_version:'synthetic',safety_note:'隔离合成数据'};
  data.launch_recommendation = {keyword:'合成页面开发',theme:'页面开发',title:'合成上新观察',recommended_window:'等待更多证据',demand_conversations:4,matching_product_count:2,capacity_available:3,confidence:'low',market_validation_required:true,ready:false,recommended_action:'observe',suggested_product_type:'页面开发',title_direction:'明确交付范围',price_reference:'暂无有效价格样本',market_differentiation:'交付范围与验收说明',timing_basis:'样本不足，不推断发布时段',benchmark,rationale:['合成状态：先积累市场参考，再确认上新。'],evidence:[]};
  Object.assign(data.exposure_analytics,{checkpoints:[],time_buckets:[],eligible_batch_count:0,excluded_batch_count:0,confidence:'low',window_days:30,summary:'尚无成熟批次'});
  Object.assign(data.operating_plan,{effective_batch_count:0,spent_this_week:0,planned_this_week:0,rationale:[],safety_note:'隔离测试',posture:'observe',posture_label:'继续观察'});
  const base = structuredClone(data.products[0]);
  const names = ['合成品牌页面设计','合成小程序页面开发','合成数据可视化','合成项目部署服务','合成移动端适配','合成组件维护'];
  data.products = names.map((title,i)=>({...structuredClone(base),external_id:`synthetic-product-${i+1}`,title,price:[800,1200,600,300,500,null][i],monitoring_enabled:i!==1,linked_projects:i===0?base.linked_projects:[],converted_project_count:i===0?1:0,revenue_total:i===0?2100:0,profit_total:i===0?1650:0,project_expense_total:i===0?450:0,deal_rate:i===0?25:0}));
  data.summary.monitored_products=5; data.summary.active_products=6; data.summary.snapshot_days=7;
  data.modification_suggestions=[{external_id:base.external_id,title:names[0],variable:'title',reason:'合成测试：比较标题说明',suggested_change:'补充交付范围',confidence:'low',blocked_reason:null,benchmark_keyword:null,market_evidence:[],market_gap:null,reference_price_range:null,confidence_basis:['合成测试证据，不代表真实建议'],evidence_sources:['内部快照']}];
  data.launch_plans=[{id:'synthetic-plan',keyword:'合成页面开发',theme:'页面开发',title:'合成服务说明整理',recommended_window:'等待人工安排',rationale:[],evidence:[],confidence:'low',status:'planned',created_at:'2026-09-17T00:00:00Z',updated_at:'2026-09-17T00:00:00Z'}];
  if(caseName==='long')data.products[0].title='合成多端页面设计开发与历史资料维护'.repeat(8);
  if(caseName==='pending'){Object.assign(data.products[0],{ownership_status:'pending',monitoring_enabled:false,last_collection_status:'pending',last_collected_at:null,snapshot_count:0});data.summary.pending_products=1;data.summary.monitored_products=4;}
  if(caseName==='paused'){data.products.forEach(p=>p.monitoring_enabled=false);data.summary.monitored_products=0;}
  if(caseName==='failed')Object.assign(data.products[0],{last_collection_status:'failed',last_error_code:'access_verification',last_error_detail:'合成采集失败：需要人工验证，未继续访问平台。',last_attempt_at:'2026-09-17T02:00:00Z'});
  if(caseName==='sample'){data.market_reference.current_sample={id:'synthetic-market',keyword:'合成页面开发',sample_date:'2026-09-17',source:'edge_codex',captured_at:'2026-09-17T02:00:00Z',result_count:2,note:'隔离样本',results:[{position:1,title:'合成公开页面服务',price:200,tags:['开发']},{position:2,title:'合成无报价服务',price:null,tags:[]}]};data.market_reference.update_completed=true;data.market_reference.last_updated_at='2026-09-17T02:00:00Z';}
  if(caseName==='empty'){data.products=[];data.summary.monitored_products=0;data.summary.active_products=0;data.summary.snapshot_days=0;data.modification_suggestions=[];data.launch_plans=[];data.launch_recommendation.demand_conversations=0;data.launch_recommendation.matching_product_count=0;}
  if(['batch','legacy-batch','invalid-batch'].includes(caseName)){
    const batch=trafficBatch(caseName==='legacy-batch') as ProductTrafficBatchView;
    if(caseName==='invalid-batch')Object.assign(batch,{status:'invalidated',has_reliable_baseline:false,analysis_eligible:false,analysis_tier:'fact_only',analysis_tier_label:'事实记录',baseline_quality:'missing',baseline_quality_label:'基线无效',due_checkpoint:null,due_ready:false});
    data.traffic_batches=[batch];Object.assign(data.traffic_summary,{batch_count:1,active_batch_count:1,observation_batch_count:1,effective_batch_count:batch.analysis_eligible?1:0});
  }
  return data;
}

function trafficBatch(legacy = false) {
  const start='2026-09-12T04:00:00Z';
  const sequence=legacy?['h1','h6','h24','h72']:['h1','h6','h24','h48'];
  const products=[1,2].map((id)=>({external_id:`synthetic-product-${id}`,title:`合成批次商品 ${id}`,baseline_browse_count:100,baseline_collect_count:0,baseline_want_count:0,baseline_inquiry_count:0,baseline_captured_at:start,baseline_source:'manual',latest_checkpoint:'h24',latest_browse_count:100+25*id,latest_collect_count:0,latest_want_count:id,latest_inquiry_count:id,browse_delta:25*id,collect_delta:0,want_delta:id,inquiry_delta:id,exploratory_points:[],checkpoints:[1,6,24].map((hours,i)=>({checkpoint:`h${hours}`,hours,recorded_at:new Date(Date.parse(start)+hours*3600000).toISOString(),browse_count:100+[5,15,25][i]*id,collect_count:0,want_count:i===2?id:0,inquiry_count:i===2?id:0,browse_delta:[5,15,25][i]*id,collect_delta:0,want_delta:i===2?id:0,inquiry_delta:i===2?id:0}))}));
  return {id:legacy?'synthetic-legacy-batch':'synthetic-batch',plan_slot_id:null,status:'observing',planned_at:start,started_at:start,completed_at:'2026-09-12T05:00:00Z',updated_at:start,baseline_prepared_at:start,recording_mode:'standard',attribution_status:'clean',invalidated_at:null,invalidation_reason:null,invalidation_label:null,checkpoint_collection_mode:'manual',observation_window_hours:legacy?72:48,terminal_checkpoint:legacy?'h72':'h48',checkpoint_sequence:sequence,is_legacy_protocol:legacy,observation_title:legacy?'合成历史 72h 批次':'合成实际时间 48h 批次',checkpoint_jobs:[],has_reliable_baseline:true,baseline_expires_at:null,baseline_status:'used',baseline_status_label:'合成可靠 T0',can_prepare_baseline:false,can_start:false,planned_actual_delta_minutes:0,planned_actual_delta_label:null,needs_replan:false,replan_reason:null,actual_cost:6,total_exposure:300,note:'合成观察数据，不代表平台因果增量',products,completed_checkpoints:['h1','h6','h24'],due_checkpoint:legacy?'h72':'h48',due_at:legacy?'2026-09-15T04:00:00Z':'2026-09-14T04:00:00Z',due_ready:true,checkpoint_progress:3,baseline_age_minutes:0,baseline_quality:'fresh',baseline_quality_label:'可靠 T0',baseline_quality_detail:'合成手工基线，费用保留在批次层',overlap_warning:null,start_blocked:false,start_blocked_reason:null,start_blocked_until:null,browse_delta:75,collect_delta:0,want_delta:3,inquiry_delta:3,inquiry_conversion_rate:4,cost_per_browse:0.08,cost_per_inquiry:2,observation_checkpoint:'h24',observation_hours:24,time_bucket:'12',data_quality:'mature',analysis_eligible:true,analysis_tier:'decision_grade',analysis_tier_label:'决策级观察',analysis_confidence:'low',exploratory_available:false,exploratory_reference_source:null,exploratory_reference_label:null,exploratory_reference_at:null,exploratory_through_label:null,exploratory_through_at:null,observed_browse_change:75,observed_collect_change:0,observed_want_change:3,observed_inquiry_change:3,natural_browse_low:null,natural_browse_high:null,natural_sample_size:0,natural_item_count:0,control_browse_expected:null,control_item_count:0,control_adjusted_browse_change:null,directional_browse_low:null,directional_browse_high:null,exploratory_summary:null,analysis_limitations:['合成记录，仅检查原有曲线和切换，不代表真实归因'],exploratory_points:[],checkpoint_metrics:[1,6,24].map((hours,i)=>({checkpoint:`h${hours}`,hours,batch_count:1,browse_delta:[15,45,75][i],collect_delta:0,want_delta:i===2?3:0,inquiry_delta:i===2?3:0,inquiry_conversion_rate:i===2?4:0,average_browse_delta:[15,45,75][i],average_inquiry_delta:i===2?3:0})),created_at:start};
}
