import type { BusinessAnalysisOverview, BusinessAnalysisRecommendation } from '../src/data/businessAnalysisService';
import type { LedgerSnapshot } from '../src/types';
export const analysisTestTime = '2026-09-18T04:00:00Z';
export function analysisFixture(state='normal') {
 const empty=state==='empty';
 const ledger={customers:empty?[]:[{id:'qa-customer',name:'合成验收客户',source:'xianyu',level:'C',followUpStatus:'contacted',channelIdentities:[]},{id:'qa-orphan',name:'合成交付客户',source:'other',level:'B',followUpStatus:'won',channelIdentities:[]}],projects:empty?[]:[{id:'qa-project',name:'合成客户管理工作台',customerId:'qa-customer',category:'client',totalAmount:12000,status:'in_progress',startDate:'2026-08-01',dueDate:'2026-09-30',progress:40,accent:'green',estimatedHours:50},{id:'qa-project-2',name:'合成预约页面交付',customerId:'qa-orphan',category:'client',totalAmount:8000,status:'completed',startDate:'2026-08-01',dueDate:'2026-09-15',progress:100,accent:'blue',estimatedHours:20}],payments:empty?[]:[{id:'qa-income-1',projectId:'qa-project',customerId:'qa-customer',amount:4000,paidAt:'2026-08-15',dueAt:'2026-08-15',status:'confirmed',type:'deposit'},{id:'qa-income-2',projectId:'qa-project-2',customerId:'qa-orphan',amount:8000,paidAt:'2026-09-10',dueAt:'2026-09-10',status:'confirmed',type:'final'}],expenses:empty?[]:[{id:'qa-expense-1',projectId:'qa-project',name:'合成八月工具费用',amount:1000,paidAt:'2026-08-16',category:'software'},{id:'qa-expense-2',projectId:'qa-project',name:'合成九月工具费用',amount:1800,paidAt:'2026-09-10',category:'software'}],tasks:[],attachments:[],changeOrders:[],settlementIssues:[],logs:[],completedOrderCount:0,settings:{xianyuStartedAt:'2026-08-01',monthlyIncomeGoal:10000,profileName:'合成验收账户',notificationsEnabled:false}} as LedgerSnapshot;
 const sum=(rows:{amount:number}[])=>rows.reduce((n,r)=>n+r.amount,0);
 const income=(month:string)=>sum(ledger.payments.filter(p=>p.paidAt.startsWith(month)));
 const expense=(month:string)=>sum(ledger.expenses.filter(p=>p.paidAt.startsWith(month)));
 const period=(current:number,previous:number)=>({current,previous,delta:current-previous,change_percent:previous?(current-previous)/previous*100:null,direction:current===previous?'flat' as const:current>previous?'up' as const:'down' as const,unit:'元'});
 const currentIncome=income('2026-09'),previousIncome=income('2026-08'),currentExpense=expense('2026-09'),previousExpense=expense('2026-08');
 const recommendations:BusinessAnalysisRecommendation[]=empty?[]:['pending','accepted','observing','review_due','completed','ignored'].map((lifecycle,i)=>({id:'qa-rec-'+i,analysis_id:'qa-analysis',analysis_snapshot_time:analysisTestTime,source_key:'qa-source-'+i,domain:i%2?'finance':'projects',entity_type:'project',entity_id:'qa-project',entity_label:'合成客户管理工作台',target_scope:'entity',priority:i<2?'high':'medium',title:['核对下一阶段回款安排','复查本月工具投入','观察交付范围变化','完成上期回款复盘','归档交付改进记录','暂缓新增工具投入'][i]+(state==='long'?' · 长标题与来源信息完整显示'.repeat(5):''),problem:'待回款仍需人工核对',action:'按原合同核对交付范围与回款节点，实际操作由经营者确认。',reason:'分析只读取已确认账本与项目记录，不将任务完成视为客户验收。',data_source:[i%2?'统一账本':'项目记录'],confidence:'medium',observe_period:'7d',observe_days:7,status:lifecycle==='review_due'?'observing':lifecycle as BusinessAnalysisRecommendation['status'],lifecycle_status:lifecycle as BusinessAnalysisRecommendation['lifecycle_status'],version:1,user_note:'',target_page:i%2?'经营记录':'项目管理',execution_mode:'manual',evidence_refs:[i%2?'finance.income.current':'projects.outstanding_receivables'],accepted_at:i?analysisTestTime:null,started_at:i>1?analysisTestTime:null,observe_until:i>1?'2026-09-25T04:00:00Z':null,completed_at:lifecycle==='completed'?analysisTestTime:null,baseline_metrics:i?{captured_at:analysisTestTime,snapshot_hash:'synthetic',values:[{key:'balance',label:'项目待回款',value:8000,unit:'元',evidence_ref:'projects.outstanding_receivables'}]}:null,result_metrics:null,outcome:lifecycle==='completed'?'inconclusive':null,actual_cost:null,actual_hours:null,user_conclusion:'',execution_ref_type:null,execution_ref_id:null,stale:state==='stale',can_accept:lifecycle==='pending'&&state!=='stale',can_ignore:lifecycle==='pending',can_start:lifecycle==='accepted'&&state!=='stale',can_complete:lifecycle==='observing'||lifecycle==='review_due'}));
 const signal={current:0,delta_7d:null,comparison_products:0,available:false,unit:'次'};
 const overview:BusinessAnalysisOverview={summary:empty?'尚无经营记录；录入真实项目与收支后再分析。':'本月确认收入高于上月，仍有项目待回款。先核对合同节点，再决定下一步行动。',metrics:{finance:{income:period(currentIncome,previousIncome),expenses:period(currentExpense,previousExpense),profit:period(currentIncome-currentExpense,previousIncome-previousExpense),all_time_income:sum(ledger.payments),all_time_expenses:sum(ledger.expenses),all_time_profit:sum(ledger.payments)-sum(ledger.expenses),confirmed_payment_count:ledger.payments.length,expense_count:ledger.expenses.length},projects:{total:ledger.projects.length,status_counts:empty?{}:{in_progress:1,completed:1},active_projects:empty?0:1,completed_projects:empty?0:1,overdue_projects:0,contract_total:ledger.projects.reduce((n,p)=>n+p.totalAmount,0),confirmed_income:sum(ledger.payments),outstanding_receivables:empty?0:8000},customers:{total:ledger.customers.length,follow_up_status_counts:empty?{}:{contacted:1,won:1},won_customers:empty?0:1,active_last_30d:0,stale_or_missing_contact_30d:ledger.customers.length,latest_contact_at:null,conversation_customers:0,latest_message_at:null},products:{owned_products:0,monitored_products:0,active_products:0,status_counts:{},latest_published_at:null,snapshot_days:0,snapshot_coverage_percent:0,exposure:signal,inquiries:signal,converted_projects:signal,platform_sold_count:0,inquiry_rate_percent:null}},insights:[{id:'qa-insight',domain:'projects',severity:'warning',title:'合同仍有未收余额',reason:'待回款来自合同总额扣除确认收款，尚需人工检查约定节点。',evidence_refs:['projects.outstanding_receivables']}],recommendations,data_sources:[{id:'finance',label:'统一账本',source_type:'ledger',tables:['payments','expenses'],fields:['amount','paidAt'],available:true,record_count:ledger.payments.length+ledger.expenses.length,latest_at:empty?null:'2026-09-10T04:00:00Z',note:'确认收入与支出；本月按北京时间计算'},{id:'projects',label:'项目记录',source_type:'ledger',tables:['projects'],fields:['totalAmount','status'],available:true,record_count:ledger.projects.length,latest_at:empty?null:analysisTestTime,note:'合同与项目状态'},{id:'products',label:'本人商品快照',source_type:'sqlite',tables:[],fields:[],available:false,record_count:0,latest_at:null,note:'尚无已核验的本人商品快照'}],future_fields:[],data_gaps:['商品趋势缺少可比较快照；无法计算曝光变化。'],predictions:[],prediction_run_id:null,prediction_snapshot_hash:null,analysis_method:'evidence_rules_v1',ledger_revision:1,period:{timezone:'Asia/Shanghai',current_month_start:'2026-09-01',current_month_end:'2026-09-30',previous_month_start:'2026-08-01',previous_month_end:'2026-08-31',product_change_window_days:7},generated_at:analysisTestTime,analysis_id:empty?null:'qa-analysis',record_status:empty?'live':'completed',provider:null,model:null,ai_status:state==='failed'?'failed':'not_requested',fallback_used:false,snapshot_time:analysisTestTime,is_stale:state==='stale',ai_error:state==='failed'?{code:'synthetic_timeout',message:'模拟模型未完成推理',retryable:true}:null};
 return {ledger,overview,recommendations};
}
