// Synthetic frontend fixture only. Never connected to a business database.
export const referenceProductFixture = {
  collection:{configured:false,schedule:'隔离测试',timezone:'Asia/Shanghai',can_collect_today:false,next_collection_at:null,last_run:null,latest_attempt:null,attempts:[],safety_note:'合成数据，禁止远程采集'},
  summary:{monitored_products:1,active_products:2,pending_products:0,excluded_products:0,needs_attention:0,traffic_candidates:0,snapshot_days:0,active_projects:0,delivery_capacity:3},
  products:[1,2].map(id=>({external_id:`synthetic-product-${id}`,title:`合成商品 ${id} · 页面设计与开发`,price:100,status:'active',monitoring_enabled:id===1,monitor_source:'test',ownership_status:'owned',ownership_source:'test',last_attempt_at:null,last_collection_status:'waiting',last_error_code:null,last_error_detail:null,last_collected_at:null,browse_count:120,raw_browse_count:121,collection_views_excluded:1,collect_count:2,want_count:3,sold_count:0,browse_delta:null,inquiry_count:4,inbound_message_count:5,converted_project_count:0,revenue_total:0,profit_total:0,project_expense_total:0,project_refund_total:0,profit_is_realtime:true,linked_projects:[],inquiry_rate:3.3,deal_rate:0,snapshot_count:0,freshness_days:null,data_quality:'low',data_gaps:[],traffic_cooldown_until:null,modification_observation_until:null,recent_windows:[],history:[],recommendation:null,actions:[]})),
  candidates:[],recommendations:[],publish_timing:{sample_size:0,confidence:'low',summary:'尚无合成趋势样本',windows:[]},demand_opportunities:[],
  operating_plan:{slots:[],weekly_budget:0,data_quality:'low',change_summary:'无计划',rules_version:'test',version:1},
  traffic_batches:[],traffic_summary:{batch_count:0,effective_batch_count:0,active_batch_count:0,planned_batch_count:0,observation_batch_count:0,due_checkpoint_count:0,spent_this_week:0,analysis_stage:'learning',analysis_summary:'无投流数据'},
  exposure_analytics:{},market_reference:{mode:'recommended',custom_keyword:'',common_keywords:[],recommendations:[],selected_keyword:'',items:[],safety_note:'合成数据'},launch_recommendation:{},launch_plans:[],modification_suggestions:[],modification_experiments:[],
};
referenceProductFixture.products[0].history = Array.from({length:7},(_,i)=>({date:`09-${String(i+1).padStart(2,'0')}`,browse_count:30+i*15})) as never[];
Object.assign(referenceProductFixture.products[0],{last_collection_status:'success',last_collected_at:'2026-09-07T00:00:00Z',snapshot_count:7,freshness_days:2,revenue_total:2100,profit_total:1650,project_expense_total:450,converted_project_count:1,linked_projects:[{project_id:'qa-project',project_name:'合成关联项目',relation_source:'project_binding',latest_confirmed_at:'2026-09-09T02:30:00Z',confirmed_total:2100,net_confirmed_total:2100,expense_total:450,refund_total:0,profit_total:1650}]});
